### ISSUE TITLE
Creation of Sample Dashboard

### ISSUE THREAD

**Issue by KristinaBorch** [SORMAS-Foundation/SORMAS-Project#10723]
### Situation Description & Motivation

For improved monitoring of samples, a samples dashboard is needed. The structure should be similar to the surveillance and contact dashboard. Please note, before implementation it should be possible to add samples to the person view without another entity https://github.com/hzi-braunschweig/SORMAS-Project/issues/10714.

### High-Level Explanation

On the top of the dashboard, there should be for this epi-week, the epi-week before, region and disease. The filter epi-week should be set to the current epi-week compared to the epi-week before. Below the filters are five elements which provide an overview of the sample situation. The upper row should contain the first three elements and the last two elements should be placed in a second row. The elements are a overview of all samples, all positive samples per disease, all negative samples per disease, specimen condition and shipment status. Below those five elements within the blue area there should be a graph for a weekly sample overview and next o it on the right, there should be a sample status map, showing where the samples are located. Additionally, when hovering over arrows within the dashboard a description/interpretation should appear.

### Tasks

- [x] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10721
- [x] https://github.com/hzi-braunschweig/SORMAS-Project/issues/11411
- [x] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10738
- [x] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10744
- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10745
- [x] #11415

### Duplicates

- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10734
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10736
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10740
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10733

### Additional Information

![grafik](https://user-images.githubusercontent.com/23217632/219331942-4a43ccd7-36ce-42d5-bf44-1be7c5d34cda.png)

**Comment by bernardsilenou** [comment]
All associates issues implemented and approved
