### ISSUE TITLE
Refinement of Samples 

### ISSUE THREAD

**Issue by KristinaBorch** [SORMAS-Foundation/SORMAS-Project#10762]
### Situation Description & Motivation

The Sample module should be refined for improved sample management. Please note, before implementation it should be possible to add samples to the person view without another entity https://github.com/hzi-braunschweig/SORMAS-Project/issues/10714.

High-Level Explanat

### High-Level Explanation

For improved sample management the document cad and document templates card should be added to the right side below additional tests card. Next to that, for the documents templates card, a new area in the document template configurations is needed. 

### Tasks

- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10763
- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10765
- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10766

### Additional Information

![image](https://user-images.githubusercontent.com/98821699/198036063-96511b04-01cc-49f8-84f5-2d23ed7792b6.png)
