### ISSUE TITLE
Moving all SORMAS Repositories to different organization

### ISSUE THREAD

**Issue by SORMAS-JanBoehme** [SORMAS-Foundation/SORMAS-Project#11863]
As dicussed in our meeting some time ago we need to move the repositories to a different account.

To avoid any issues with ongoing release cycles, the switch will happen on April 27th, 2023 after the current sprint is finished.

### Preparation todos

- [x] List of repositories to be moved @SORMAS-JanBoehme 
- [x] #11905
- [x] Re-organize team structure @SORMAS-JanBoehme 
- [x] Create teams & single permissions in new organization @SORMAS-JanBoehme 
- [x] Announcement @SORMAS-JanBoehme 
- [x] Guide for developers on how to change the origin --> TEC team
- [x] List of systems/external resources where links need to be adjusted @fhauptmann @SORMAS-JanBoehme 
- [x] #11900
- [x] https://github.com/hzi-braunschweig/SORMAS-Docker/issues/502

### Announcement for dev community after migration was done

> Dear SORMAS contributors. 
> 
> We have successfully migrated all SORMAS repositories to the SORMAS-Foundation organization on Github. This means you have to update the remote origin of your local repositories. To do so, use the following command for the SORMAS-Project repository:
> 
> HTTPS: `git remote set-url origin https://github.com/sormas-foundation/SORMAS-Project.git`
> SSL: `git remote set-url origin git@github.com:SORMAS-Foundation/SORMAS-Project.git`
> 
> Adjust the URL accordingly for other repositories.
> Alternatively you can change the remote origin URL in the GitHub client's "Repository settings" dialog.

### Later

* Update links from SORMAS-Project wiki to readme files
* Docker hub (see also #11700)

### Repository List

https://github.com/hzi-braunschweig/SORMAS-Project
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Docker
Action: Move

https://github.com/hzi-braunschweig/SORMAS-DHIS
Action: Move

https://github.com/hzi-braunschweig/sormas-demis-adapter 
Action: Move

https://github.com/hzi-braunschweig/sormas-survnet-interface
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Angular
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen
Action: Move

https://github.com/hzi-braunschweig/SORMAS-central-data
Action: Move

https://github.com/hzi-braunschweig/EpiDataGen
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Security
Action: Move

https://github.com/hzi-braunschweig/S2S-Testbed
Action: Move

https://github.com/hzi-braunschweig/SORMAS-data-generator
(Last change 3 years ago and seems to have the same purpose as "EpiDataGen" - still needed?)
Action: Move and Archive

https://github.com/hzi-braunschweig/sormas_hzi_ansible
(private and no changes for nearly a year - still needed?)
Action: Move

https://github.com/hzi-braunschweig/DEMIS-Test_Environment
(fork of https://github.com/gematik/DEMIS-Test_Environment - still needed?)
Action: Move

https://github.com/hzi-braunschweig/sormas-issuetracker
(fork of https://github.com/healthIMIS/sormas-issuetracker)
Action: Move and Archive

https://github.com/hzi-braunschweig/SORMAS-RFC
Action: Move and Archive

https://github.com/hzi-braunschweig/SORMAS-Switzerland
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Glossary
(last change 2 years ago - still needed?)
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Luxembourg
Action: Move

https://github.com/hzi-braunschweig/SORMAS-Stats-sitrep
Achtion: Do not move and delete

https://github.com/hzi-braunschweig/SORMAS-ansible
(last change 3 years ago - still needed?)
Action: Move

Repositories will be moved to this organization, names will stay the same:
https://github.com/SORMAS-Foundation

Projects (i.e. backlog) attached to the organization will be copied to the new organization.

This issue is meant to inform everybody and pool information about things we need to consider for everything to work smoothly.

Pings:
@markusmann-vg @bernardsilenou @MateStrysewske @MartinWahnschaffe @fhauptmann @GouthamVadivelmurugan @Candice-Louw @SORMAS-ChristopherMeyer 

Project Boards:
SORMAS Investigation Board - https://github.com/orgs/hzi-braunschweig/projects/13 (still needed?)
SORMAS Product Backlog - https://github.com/orgs/hzi-braunschweig/projects/14/views/1 (move)
SORMAS Epic Board - https://github.com/orgs/hzi-braunschweig/projects/8/views/1 (still needed?)
SORMAS Approval Board - https://github.com/orgs/hzi-braunschweig/projects/10 (no longer needed)
SORMAS Team 2 - DEV - Iteration Backlog - https://github.com/orgs/hzi-braunschweig/projects/3 -Convert to new board in new org
SORMAS Team 4 - TEC - Iteration Backlog - https://github.com/orgs/hzi-braunschweig/projects/1 - Convert to new board in new org

**Comment by bernardsilenou** [comment]
@SORMAS-JanBoehme 
* https://github.com/hzi-braunschweig/SORMAS-Stats-sitrep  can be deleted, it's now a sub-repository under https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen 
* https://github.com/hzi-braunschweig/SORMAS-data-generator and https://github.com/SORMAS-Foundation/SORMAS-Stats-old can be archived after migration. They are similar to https://github.com/hzi-braunschweig/EpiDataGen
* https://github.com/hzi-braunschweig/SORMAS-Glossary can be migrated and kept

**Comment by SORMAS-JanBoehme** [comment]
I have set up a MS Teams video call that everybody who wants to can join so we can check everything directly and address any issues that come up:

I will start it on April 27th - 1 p.m. (CEST)

https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODk2OTBhMTctN2NiNy00Mjc4LThjNTAtNjAwMDQ3ZmI4N2Jj%40thread.v2/0?context=%7b%22Tid%22%3a%2245842f0e-87e4-450a-bf9b-20ad505c1715%22%2c%22Oid%22%3a%224e74f3d1-8195-435b-b1b8-5bf9e7360553%22%7d

**Comment by markusmann-vg** [comment]
@SORMAS-JanBoehme We just discussed it in the ART Daily. Currently there are preparations ongoing which we (NLI & VG) would like to present and discuss in the meeting you scheduled. Goal of the meeting should be that we have a plan when to do the moving.
Please do the invitation to this meeting via outlook/Teams as we should not have a public link to the meeting here in GitHub. Thank you

**Comment by SORMAS-JanBoehme** [comment]
@markusmann-vg Sure, I can schedule another meeting. The one I posted was meant to be a possibility for everyone to be present when the work is being done. So it would be too late for a preparation meeting. This is why I posted it here so everyone could attend without having to be invited first.

I'll remove this link and resend it via e-mail together with a second preparation meeting.

**Comment by fhauptmann** [comment]
> What needs to be considered (brainstorming from my perspective):
> 
>     1. Set up of permission structure in the new organisation with appropriate teams and roles.
> 
>     2. Move the repositories with all information (like tickets, wiki) to the new organisation.
>        
>        * Configure permissions for the moved Git repos.
>        * Make sure that all automation in Github still works.
> 
>     3. Move or recreate Project Boards.
> 
>     4. Rewrite the origin URL in local Git repos: Give users/developers guidance how to do this.
> 
>     5. Rewrite all Git Repo URLs in Jenkins jobs and origin URL in Git repos on Jenkins VM.
> 
>     6. Change URLs in documentation (not outdated pages, but active link overviews and current iteration documentation).

7. Create automation users and add credentials to all automation tasks

**Comment by MartinWahnschaffe** [comment]
https://docs.github.com/de/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by bernardsilenou** [comment]
@SORMAS-JanBoehme 
Please let us not migrate https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen now, but do it at a later phase.

**Comment by MartinWahnschaffe** [comment]
All repositories have been moved and all projects have been imported now.
Looks like at least my GitHub client automatically changes the origin URL.

Still pending:
* Update of URLs in Jenkins
* Update of URLs in SORMAS-Project and wiki (PR of https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11900 needs to be rebased and merged)
* Merging of branch that updates URLs in SORMAS-Docker

**Comment by bernardsilenou** [comment]
@SORMAS-JanBoehme  Just saw https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11863#issuecomment-1562575438 after our meeting, hope no need to reply

**Comment by StefanKock** [comment]
Migration was done (afaik)
