### ISSUE TITLE
Add 'REPORT' as a new deletion reference for automatic and permanent deletion [2]

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12067]
### Problem Description

Currently, the deletion references implemented are CREATION, ORIGIN, END AND MANUAL_DELETION (https://github.com/SORMAS-Foundation/SORMAS-Project/wiki/Manual-&-Automatic-Deletion#deletion-references).

According to an official decision, the reference date for the automatic deletion of a case has to be triggered by another reference date, which should be added to the deletion references and be called 'REPORT'.

### Proposed Change

- the default deletion reference for cases should be filled with 'casedata.reportdate' - therefore 'REPORT' needs to be added as a new deletion reference in the 'deleteconfiguration'.

### Added Value/Benefit

According to the decision of the State Ministry of Health and Care it is necessary to change the new entry to ensure, that the automatic deletion of a case is performed after 10 years after reporting the case.

### Acceptance Criteria

- [x] the 'deletionperiod' associated with this reference should have the same validations as the rest of the deletion references (i.e. can not be lower than 7 days);
- [x] the automatic deletion of a case is requested to be performed after 10 years after reporting the case (the deletion period is set from the DB; this is not pre-set and needs to be configured when the deletion process is configured, from the 'deleteconfiguration' table);
- [x] pre-requisites for the deletion based on report date:
- Case has been created with report date (mandatory fields so all cases will have one);
- Case stayed for 10 years in case directory (deletionpersiod set in the deleteconfiguration);
- Case has not been deleted due to other reasons (any of the other references for deletion);
- Automatic Case deletion is triggered by report date;
- [x] the automatic deletion based on the new reference should continue to do the permanent deletion immediately after (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/8293);
- [x] the date when the entity is going to be automatically deleted should continue to be displayed but calculated based on the entity report date (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/7240);
- [x] based on #11964 the deletion reference of 'REPORT' is currently specifically requested only for cases; however, for consistency, it should be introduced as an **option**  for all entities that the automatic and permanent deletion is currently implemented for and configured/used when desired;

### Additional Information

Current ticket is created as a result of #11964 - which was closed as a duplicate as discussed with @markusmann-vg

**Comment by adinaflorea9** [comment]
I am reopening the ticket due to an exception that is thrown when trying to run the automatic deletion based on 'REPORT' as a deletion reference - event participants can not be deleted based on 'REPORT' as a deletion reference. In the ticket it was mentioned that the 'REPORT' deletion reference should be added as an option for all entities (last checkbox from the acceptance criteria).

Logs from the local machine:
[Error msers surveillance officer.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11870694/Error.msers.surveillance.officer.txt)

**Comment by leventegal-she** [comment]
@adinaflorea9 
Event participant does not have report date, this means deletion reference REPORT can't be applied for it.

**Comment by adinaflorea9** [comment]
@leventegal-she thank you for pointing that - I missed that one when looking in the DB. Closing the ticket.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(2be7cd3).
