### ISSUE TITLE
[EPIC] Sending emails with attached documents

### ISSUE THREAD

**Issue by SORMAS-ChristopherMeyer** [SORMAS-Foundation/SORMAS-Project#12402]
### Feature Description

Ability to create email templates with the certain right.

The possibility to send an email to a person stored in SORMAS, which will be filled with the contents of the template.

Possibility to attach documents to these emails as well.

There must be an option to encrypt these documents.

This topic has been suggested in the past for example in  #4286 or #4278  . However, this ticket is trying to bring a clear structure to the complex implementation.

### Added Value/Benefit

Sending email templates from within the system, with the ability to attach corresponding SORMAS generated documents or uploaded documents is a useful feature. It can simplify the work for employees and ensure a fast flow of communication.

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

### Implementation Details

- [ ] Possibility to create email templates
- [ ] Possibility to select email templates in the UI
- [ ] Possibility to attach documents (PDF) to email templates
- [ ] Display a history of sent documents
- [ ] Creation of new user rights "creating mail templates" "sending mails", "sending documents"
- [ ] configurability of the email settings

### Mockups

will be added
