### ISSUE TITLE
[EPIC] Disease dashboard Merge back to SORMAS main branch

### ISSUE THREAD

**Issue by isaacanip** [SORMAS-Foundation/SORMAS-Project#12880]
### Situation Description & Motivation

This is a Ghana feature requested by Ghana Health Service. The requirement of this feature is to display a disease page giving information on regional case count.
#### Use cases
This feature takes user to the disease dashboard page after clicking on disease under the surveillance dashboard. See image below:
1. User goes to the surveillance dashboard and clicks on the more (...) option for a particular disease.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/20621b67-7512-4c7d-aace-9edd161fe255)
2. After clicking on the more option in (1), the disease dashboard comes up with the various regional disease burden and disease detail map.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/d931fb38-58b0-44af-aeec-ee0294751360)

### Tasks

This EPIC details the task requirements (listed in the Acceptance Criteria section) to merge back to SORMAS main branch.
[#835](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/835)
[#1529](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/1529)
[#6](https://github.com/ePareto-Information-System/SORMAS-Project/issues/6)

- [x] ePareto: Creates the Epic for Disease Dashboard on SORMAS GitHub Repository from ePareto GitHub account(Until 10th January 2024).
- [ ] ePareto: Create a feature branch/fork (with EPIC #) from the development branch and inform SF(Until 11th January 2024).
- [ ] ePareto: Import or integrate the code into the feature branch/fork (Until 17th January 2024).
- [ ] ePareto: Start QA by checking the code (Until 22nd January 2024).
- [ ] ePareto: Perform final commit into feature branch/fork and inform SF (Until 23rd January 2024)
- [ ] SORMAS Foundation: Take the feature branch/fork, test code locally and when everything is fine ePareto will do a Pull Request to merge with the development branch (Until 29th January 2024).
- [ ] SORMAS Foundation: Approve the request to the development branch (Until 31st January 2024).
- [ ] SORMAS Foundation: Merge the Development branch into the master branch when the new version of SORMAS is released(The date is not defined yet).
