### ISSUE TITLE
[EPIC] Password reset Merge back to SORMAS main branch.

### ISSUE THREAD

**Issue by isaacanip** [SORMAS-Foundation/SORMAS-Project#12881]
### Situation Description & Motivation

Ghana Health Service (GHS) requested that SORMAS users should be able to generate their own password. According to GHS, the default password generated by the SORMAS application is not easy to easily remember.

The feature allows user to enter current password, New password and verify new password.
#### Use cases
1. User clicks on the user settings on the main menu.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/0c9fa60e-875a-4a53-b3c1-44dce4b121e7)
2. The user setting form comes as seen below. User then clicks on the "Create new password"
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/7ffe9bad-8711-48a9-971c-0e0bbe93ad8c)
3. The Change password form comes up and user update the available fields with current password, new password and confirm new password.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/24320b25-88c6-4787-9a9e-7ad79f58d199)
4. Type the required values in the fields and click on the "Save" button. When successful, a message prompt (as seen below) comes on the screen.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/3c5e626e-1c4a-40e8-9b45-efc0e8e08484)
5. If password does not match, an alert message pops up as seen in the image below:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/60930711/476b861e-7de0-441b-ac2a-5eea7ca686ee)

### Tasks

- [#1091](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/1091)
- [#1092](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/1092)
- [#3702](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/3702)
- [#6](https://github.com/ePareto-Information-System/SORMAS-Project/issues/21)

- [x] ePareto: Creates the Epic for Password reset on SORMAS GitHub Repository from ePareto GitHub account(Until 10th January 2024).
- [ ] ePareto: Create a feature branch/fork (with EPIC #) from the development branch and inform SF(Until 11th January 2024).
- [ ] ePareto: Import or integrate the code into the feature branch/fork (Until 17th January 2024).
- [ ] ePareto: Start QA by checking the code (Until 22nd January 2024).
- [ ] ePareto: Perform final commit into feature branch/fork and inform SF (Until 23rd January 2024)
- [ ] SORMAS Foundation: Take the feature branch/fork, test code locally and when everything is fine ePareto will do a Pull Request to merge with the development branch (Until 29th January 2024).
- [ ] SORMAS Foundation: Approve the request to the development branch (Until 31st January 2024).
- [ ] SORMAS Foundation: Merge the Development branch into the master branch when the new version of SORMAS is released(The date is not defined yet).

**Comment by isaacanip** [comment]
The EPIC document for the **Password Reset** has been updated to incorporate the Keycloak integration, enabling users to be redirected to Keycloak's password reset feature.
