### ISSUE TITLE
Feedback for document generation

### ISSUE THREAD

**Issue by JonasCir** [SORMAS-Foundation/SORMAS-Project#3544]
### Problem Description
@syntakker @Seal33 
I received feedback for the recently added document generation feature. Please note that this are general comments which likely needs refinement.

### Feedback

- [ ] Generated quarantine orders should be send directly by SORMAS via email (#4286)
- [x] Generated documents should be linked to entities and stored in SORMAS (should be possible with #3492 now)
- [x] It should be possible to generate quarantine orders for event participants (fixed with #4057)
- [ ] It should be possible to export the documents as PDF not DOCX (there is likely a way to convert doc to pdf and let the user chose what format he wants to receive)
- [x] "I think an error report will also be helpful. Sometimes empty documents are created when placeholders call for fields that are not existing in the entity or are misspelled. Thus far its a bit difficult to pin point the error that needs to be corrected in the template." (@kwa20) (improved in #4057)
- [ ] @kwa20: Do you think it would also be possible to refer to addresses in addition to home address? I guess we'd have to follow the same logic as will be implemented for samples since you can choose multiple options.

**Comment by kwa20** [comment]
I think an error report will also be helpful. Sometimes empty documents are created when placeholders call for fields that are not existing in the entity or are misspelled. Thus far its a bit difficult to pin point the error that needs to be corrected in the template.

**Comment by kwa20** [comment]
@syntakker Do you think it would also be possible to refer to addresses in addition to home address? I guess we'd have to follow the same logic as will be implemented for samples since you can choose multiple options.
