### ISSUE TITLE
[Security] Add security scanners to CI pipeline

### ISSUE THREAD

**Issue by JonasCir** [SORMAS-Foundation/SORMAS-Project#7503]
### Situation Description & Motivation

`log4shell` was a close call and we need plan ahead for the next crisis. One step forward is to make more use of static security tools and dependency analysis. Catch well known security issues at compile time.

### Tasks

- [x] #7504
- [x] #7542
- [x] #11661
- [x] #11658
- [x] #11676
- [x] #7507 
- [x] ~~Add `trivy` container scan (Needs more analysis as our current container build pipeline is sub optimal. We could setup a weekly GitHub Action scan of  the docker images published to docker hub)~~ -> Doesn't make sense now: 1. We want to integrate the docker settings into the SORMAS-Project repository. 2. The recent changes make it very likely that we will move the docker images to the github repository https://www.heise.de/news/Docker-Hub-streicht-kostenloses-Angebot-Open-Source-Projekte-muessen-handeln-7547959.html
- [x] ~~Add `owasp-dependency-check` and fail on insecure builds~~ -> Covered by trivy and sonarcloud
- [x] Checkout https://github.com/github/ossar-action --> only runs on windows
- [x] ~~Evaluate https://github.com/SUPERAndroidAnalyzer/super~~ --> outdated

### Alternatives

None really, this is the bare minimum we need to do.
