### ISSUE TITLE
[DEMIS2SORMAS] Mapping of External Messages

### ISSUE THREAD

**Issue by kwa20** [SORMAS-Foundation/SORMAS-Project#9504]
### Situation Description & Motivation

DEMIS supports messages from physicians in the form of defined [physician reports](https://simplifier.net/guide/Implementierungsleitfaden%20f%C3%BCr%20DEMIS%20Arztmeldung/Home?version=current) that allow easy transfer of data to health departments and higher health institutions. [Recently](https://github.com/hzi-braunschweig/SORMAS-Project/issues/8980), the processing of physician reports was also implemented in SORMAS. However, data from messages is not yet automatically taken over by SORMAS which would heavily simplify the processing of such messages and enhance the efficiency with which users process physician reports.

### High-Level Explanation

The FHIR profile of "Arztmeldungen" reuses some of the already known ressources like Patient and Organization but also contains many new ressources like Condition, Encounter, Immunization and QuestionnaireResponse.

Some prerequisites in SORMAS and the SORMAS-DEMIS-Adapter are necessary in order to make the data available for further mapping during the processing of messages. 

- [ ] #9646
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/64

This epic aims to list all necessary mappings separated into several topics in the physician reports profile.

### Tasks

- [x] #9733
- [ ] #9505
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/65
- [ ] #9506
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/66
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/69
- [ ] #9510
- [ ] #9533
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/67
- [ ] [DEMIS2SORMAS] Map hospitalized from physician reports to cases
- [ ] [DEMIS2SORMAS] Map Encounter from physician reports to cases
- [ ] #9531
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/68
- [ ] #9534
- [ ] [DEMIS2SORMAS] Map infectProtectFacilityGroup entries from physician reports to cases
- [ ] [DEMIS2SORMAS] Map placeExposureGroup entries from physician reports to cases
- [ ] [DEMIS2SORMAS] Map infectionEnvironmentSettingGroup entries from physician reports to cases
- [x] #11449 
- [x] #11453  
- [x] #11454 
- [x] #11456 
- [x] #11457 

Demis-Adapter ([epic](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/79))
- [x] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/80
- [x] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/81
- [x] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/82
- [x] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/83
